# Generated by Django 5.2.4 on 2025-08-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_content_post_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
