# Generated by Django 5.2.4 on 2025-08-20 07:56

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_titulo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
