# Generated by Django 5.2.4 on 2025-08-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comentario_fecha_creacion_mediafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
