# Generated by Django 5.2.4 on 2025-08-20 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comentario_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='post_media/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivo_multimedia', to='blog.post')),
            ],
        ),
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
