# Generated by Django 5.2.4 on 2025-08-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_archivomultimedia_delete_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='archivo_multimedia',
            field=models.FileField(blank=True, null=True, upload_to='post_files/'),
        ),
        migrations.DeleteModel(
            name='ArchivoMultimedia',
        ),
    ]
